export * from './accountResource.service';
import { AccountResourceService } from './accountResource.service';
export * from './customerResource.service';
import { CustomerResourceService } from './customerResource.service';
export * from './deliveryPersonnelResource.service';
import { DeliveryPersonnelResourceService } from './deliveryPersonnelResource.service';
export * from './foodOrderResource.service';
import { FoodOrderResourceService } from './foodOrderResource.service';
export * from './foodResource.service';
import { FoodResourceService } from './foodResource.service';
export * from './ingredientOrderResource.service';
import { IngredientOrderResourceService } from './ingredientOrderResource.service';
export * from './ingredientResource.service';
import { IngredientResourceService } from './ingredientResource.service';
export * from './languageResource.service';
import { LanguageResourceService } from './languageResource.service';
export * from './menuResource.service';
import { MenuResourceService } from './menuResource.service';
export * from './paymentMethodResource.service';
import { PaymentMethodResourceService } from './paymentMethodResource.service';
export * from './paymentResource.service';
import { PaymentResourceService } from './paymentResource.service';
export * from './restaurantResource.service';
import { RestaurantResourceService } from './restaurantResource.service';
export * from './restaurantWorkerResource.service';
import { RestaurantWorkerResourceService } from './restaurantWorkerResource.service';
export * from './translationResource.service';
import { TranslationResourceService } from './translationResource.service';
export * from './userResource.service';
import { UserResourceService } from './userResource.service';
export const APIS = [AccountResourceService, CustomerResourceService, DeliveryPersonnelResourceService, FoodOrderResourceService, FoodResourceService, IngredientOrderResourceService, IngredientResourceService, LanguageResourceService, MenuResourceService, PaymentMethodResourceService, PaymentResourceService, RestaurantResourceService, RestaurantWorkerResourceService, TranslationResourceService, UserResourceService];
