/**
 * propsyBackendv01 API
 * propsyBackendv01 API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FoodOrder } from './foodOrder';


export interface Customer {
    address?: string;
    city?: string;
    id?: number;
    loyaltyPoints?: number;
    mail: string;
    name: string;
    orders?: Array<FoodOrder>;
    phone?: string;
    role?: number;
}
