/**
 * propsyBackendv01 API
 * propsyBackendv01 API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Food {
    calories?: number;
    foodDescription?: string;
    id?: number;
    isGlutenFree?: boolean;
    isSpicy?: boolean;
    isVegetarian?: boolean;
    nameSlug: string;
    photoLocation?: string;
    price: number;
}
