/**
 * propsyBackendv01 API
 * propsyBackendv01 API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Food } from './food';
import { Language } from './language';


export interface Translation {
    food?: Food;
    id?: number;
    language?: Language;
    translation?: string;
}
